# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 12a536c0f1953bc389a5fb660a3c4ac2bfde2665cdf2d9403114fe3e9b1a5e9571b2b2f59431f0fe806c522a7e3dd60b282b61a122b4d789fdc040bf8dc5dc85

test:
  secret_key_base: 8563682b07c4504468c4111323ba15c98289ecd35f83024731465c520ed1243f8d26e4c4cd48100e84c3b28b66dfa736ff07800e03abc4b56f92dcaad921dc92

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
